services:
  postgres:
    container_name: api-db
    image: postgres:14.19-trixie
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-course_api}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

volumes:
  pg_data: {}